version: '3'
services:
  oidc:
    container_name: oidc
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: kcadmin
      KEYCLOAK_PASSWORD: admin

  tyk:
    container_name: tyk
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v3.2.1
    ports:
      - "8000:8000"
    environment:
      - TYK_GW_SECRET=foo
      - TYK_LOGLEVEL=debug
    depends_on:
      - tyk-redis
    volumes:
      - ./tyk/apps:/opt/tyk-gateway/apps
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/policies:/opt/tyk-gateway/policies

  tyk-redis:
    container_name: tyk-redis
    image: redis:latest
    ports:
      - "6379:6379"